services:
    main:
        build:
            dockerfile: Dockerfile
        hostname: api-test
        container_name: api-test-main
        ports:
            - "8823:80"
            - "8846:443"
        volumes:
            - ../main:/usr/share/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/http.d/default.conf
            - ./php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf
            - ./php/xdebug.ini:/etc/php/8.3/mods-available/xdebug.ini
            - ./php/php.ini:/etc/php/8.3/fpm/php.ini
            - ./php/php-fpm.conf:/etc/php/8.3/fpm/php-fpm.conf
            - ../log/nginx:/var/log/nginx/
            - ../log/app:/var/log/app/
            - ../log/php:/var/log/php8/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - TZ=Europe/Moscow
            - XDEBUG_MODE=off
        networks:
            - api-test_net
networks:
    api-test_net:
        external: true
        name: dell_net
